pr: none
trigger: none

schedules:
  - cron: "0 0 * * 1"
    displayName: Weekly fuzzing submission
    branches:
      include:
        - main
    always: true
name: $(BuildDefinitionName)_$(date:yyMM).$(date:dd)$(rev:rrr)

parameters:
  - name: platform
    type: string
    default: x64 # for fuzzing, we only use x64 for now
  - name: enableMsBuildCaching
    type: boolean
    displayName: "Enable MSBuild Caching"
    default: false
  - name: useVSPreview
    type: boolean
    displayName: "Build Using Visual Studio Preview"
    default: false

stages:
  - stage: Download
    displayName: Download From Release Pipeline
    jobs:
      - job: Download
        pool:
          name: SHINE-INT-Testing-x64
          demands: ImageOverride -equals SHINE-W11-Testing
          os: windows
        displayName: Download artifact from release pipeline and Fuzz
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'specific'
              project: 'Dart'
              definition: '76541'
              buildVersionToDownload: 'latest'
              branchName: 'refs/heads/main'
              artifactName: 'build-x64-Release'
              targetPath: '$(Build.ArtifactStagingDirectory)'
              patterns: |
                **/PowerToysSetup-*.exe
          - pwsh: |-
              & "$(build.sourcesdirectory)\.pipelines\installPowerToys.ps1"
            displayName: Install PowerToys
